env:
  es6: true
  browser: true

extends:
  - airbnb-base
  - prettier

settings:
  import/resolver:
    alias:
      extensions: ['.js']
      map:
        - ['~', './source/js']

rules:
  semi:
    - error
    - never
  comma-dangle:
    - error
    - only-multiline
    - arrays: never
      objects: always
      imports: never
      exports: never
      functions: never
  quotes:
    - error
    - backtick
  quote-props:
    - error
    - consistent
  no-unused-expressions:
    - error
    - allowTernary: true
  object-curly-newline:
    - error
    - multiline: true
      consistent: true
  no-use-before-define: off
  linebreak-style: off
  import/prefer-default-export: off
