env:
  es6: true
  browser: true

extends: 'airbnb-base'

rules:
  semi:
    - error
    - never
  comma-dangle:
    - error
    - only-multiline
    - arrays: never
      objects: always
      imports: never
      exports: never
      functions: never
  quotes:
    - error
    - backtick
  no-unused-expressions:
    - error
    - allowTernary: true
  object-curly-newline:
    - error
    - multiline: true
      consistent: true
  linebreak-style: off
  import/prefer-default-export: off
