env:
  es2021: true
  browser: true

extends:
  - eslint:recommended
  - plugin:import/recommended
  - plugin:sonarjs/recommended
  - plugin:unicorn/recommended
  - plugin:perfectionist/recommended-natural
  - plugin:jsdoc/recommended-typescript-flavor-error

plugins:
  - simple-import-sort

parserOptions:
  ecmaVersion: 2022
  sourceType: module

settings:
  jsdoc:
    mode: typescript
  import/resolver:
    alias:
      extensions:
        - .js
      map:
        - ['~', './source/scripts']

ignorePatterns:
  - build

rules:
  no-restricted-syntax:
    - error
    - selector: VariableDeclaration[kind!=let]
      message: Only let can be used for the variable declaration.
    - selector: SwitchCase > *.consequent[type!="BlockStatement"]
      message: Switch cases without blocks are forbidden.
    - selector: ExportAllDeclaration,ImportAllDeclaration
      message: Export/Import all (*) is forbidden.
    - selector: ExportNamedDeclaration[declaration!=null]
      message: Exports should be at the end of the file.
  semi:
    - error
    - never
  comma-dangle:
    - error
    - always-multiline
  quotes:
    - error
    - backtick
  quote-props:
    - error
    - consistent
  no-unused-expressions:
    - error
    - allowTernary: true
  object-curly-newline:
    - error
    - multiline: true
      consistent: true
  curly:
    - error
    - all
  object-curly-spacing:
    - error
    - always
  implicit-arrow-linebreak:
    - error
    - beside
  function-paren-newline:
    - error
    - consistent
  no-confusing-arrow:
    - error
    - allowParens: true
  require-atomic-updates:
    - error
  no-console:
    - error
    - allow:
        - warn
        - error
        - info
  arrow-parens:
    - error
    - always
  no-multiple-empty-lines:
    - error
    - max: 1
  simple-import-sort/imports:
    - error
  simple-import-sort/exports:
    - error
  perfectionist/sort-named-imports:
    - error
    - type: alphabetical
  import/exports-last:
    - error
  import/group-exports:
    - error
  import/no-default-export:
    - error
  import/first:
    - error
  import/newline-after-import:
    - error
  import/no-duplicates:
    - error
  import/extensions:
    - error
    - ignorePackages
  jsdoc/require-jsdoc:
    - error
    - checkConstructors: false
      checkGetters: true
      checkSetters: true
      contexts:
        - ArrowFunctionExpression
        - ClassProperty
        - FunctionDeclaration
        - FunctionExpression
        - MethodDefinition
  jsdoc/valid-types:
    - off
  jsdoc/require-returns-description:
    - off
  jsdoc/require-param-description:
    - off
  jsdoc/require-property-description:
    - off

overrides:
  - files:
      - commitlint.config.js
    rules:
      import/no-default-export:
        - off
  - files:
      - eleventy.config.cjs
    env:
      node: true
    rules:
      sonarjs/cognitive-complexity:
        - off
