ls:
  .dir: kebab-case
  .*: kebab-case
  .*.*: kebab-case

  .github:
    .dir: regex:[.]*[a-z]+
    .yml: kebab-case

  '*':
    CHANGELOG.md: SCREAMING_SNAKE_CASE

ignore:
  - .git
  - '**/node_modules'
  - '**/build'
  - CHANGELOG.md
