ls:
  .dir: kebab-case
  .github:
    .dir: regex:([.a-z]*)*
  .*: regex:([.a-z0-9]*)([-.][a-z0-9]+)*
  '**':
    CHANGELOG.md: SCREAMING_SNAKE_CASE

ignore:
  - .git
  - '**/node_modules'
  - '**/build'
  - CHANGELOG.md
