ls:
  .dir: regex:([.a-z]*)([-.][a-z]+)*
  .css: regex:([.a-z]*)([-.][a-z]+)*
  .html: regex:([.a-z]*)([-.][a-z]+)*
  .js: regex:([.a-z]*)([-.][a-z]+)*

ignore:
  - .git
  - node_modules
  - packages/whatislove-dev/node_modules
  - packages/whatislove-dev/build
