printWidth: 80
tabWidth: 2
useTabs: false
semi: false
singleQuote: true
quoteProps: as-needed
trailingComma: 'es5'
bracketSpacing: true
arrowParens: always
overrides:
  - files: "*.html"
    options:
      printWidth: 9999