plugins:
  - 'prettier-plugin-jsdoc'
printWidth: 80
semi: false
singleQuote: true
quoteProps: preserve
trailingComma: all
bracketSpacing: true
arrowParens: always
overrides:
  - files: '*.css'
    options:
      singleQuote: false
