plugins:
  - stylelint-prettier
  - stylelint-order
extends:
  - stylelint-prettier/recommended
  - ./stylelint.order-config.cjs
rules:
    prettier/prettier: true
    rule-empty-line-before:
      - always
      - except: first-nested
        ignore: after-comment
    number-max-precision: 2
    length-zero-no-unit: true
    no-descending-specificity: true
    declaration-empty-line-before: never
