language: node_js

node_js:
  - lts/*

cache:
  directories:
    - node_modules

branches:
  only:
    - master
    - development

install:
  - npm install

script:
  - npm run test

notifications:
  email: false
  