# get-all
GET http://localhost:3001/api/timeline HTTP/1.1

###

# get-one
GET http://localhost:3001/api/timeline/Ec6lUxnY1n HTTP/1.1

###

# post-one
POST http://localhost:3001/api/timeline HTTP/1.1
content-type: application/json

{
  "skillType": "hardSkill",
  "type": "work",
  "title": "Learn nodeJS",
  "desc": "",
  "origin": "",
  "originDesc": "",
  "link": "",
  "linkDesc": "",
  "date": "2021-01-10T14:12:47.445Z",
  "endDate": ""
}

###

# put-one
PUT http://localhost:3001/api/timeline/-AuZZD1RkS HTTP/1.1
content-type: application/json

{
  "skillType": "hardSkill",
  "type": "work",
  "title": "Learn nodeJS",
  "desc": "",
  "origin": "",
  "originDesc": "",
  "link": "",
  "linkDesc": "",
  "date": "2021-01-10T14:12:47.445Z",
  "endDate": ""
}

###

# delete-one
DELETE http://localhost:3001/api/timeline/z1pWNxkGli HTTP/1.1

###
