const ControlType = {
  BUTTON: `button`,
  CHECKBOX: `checkbox`,
  COLOR: `color`,
  DATE: `date`,
  DATETIME_LOCAL: `datetime-local`,
  EMAIL: `email`,
  // TODO (can be multiple)
  FILE: `file`,
  HIDDEN: `hidden`,
  MONTH: `month`,
  NUMBER: `number`,
  PASSWORD: `password`,
  RADIO: `radio`,
  RANGE: `range`,
  RESET: `rest`,
  SEARCH: `search`,
  SUBMIT: `submit`,
  TEL: `tel`,
  TEXT: `text`,
  TIME: `time`,
  URL: `url`,
  WEEK: `week`,
  TEXTAREA: `textarea`,
  FIELDSET: `fieldset`,
  OUTPUT: `output`,
  SELECT_ONE: `select-one`,
  SELECT_MULTIPLE: `select-multiple`,
}

export { ControlType }
