name: Continuous Delivery

on:
  push:
    branches:
      - main

concurrency:
  group: cd-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Release
        id: release
        uses: google-github-actions/release-please-action@v3
        with:
          command: manifest

  dependencies:
    name: Install Dependencies
    needs: release
    if: ${{ needs.release.outputs.release_created }}
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc

      - name: Cache Dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: cd-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            cd-

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          npm install

  build:
    name: Build
    needs: dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc

      - name: Restore Dependencies
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: cd-${{ hashFiles('**/package-lock.json') }}

      - name: Code Building
        run: |
          make build

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: build

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
