name: Lint

on:
  pull_request:
    branches:
      - development

jobs:
  linting:
    name: Linting
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: '14.x'
        java: '8.x'
    steps:
      - name: Instal NodeJS v${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Java v${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
          architecture: x64

      - name: Code Checkout
        uses: actions/checkout@v2

      - name: Code Building
        run: |
          npm run ci
          npm run build

      - name: Code Linting
        run: |
          npm run lint
