name: Notify

on:
  pull_request:
    types:
      - opened
      - reopened

jobs:
  notify:
    name: Notify
    runs-on: ubuntu-latest
    steps:
      - name: Send notification
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: markdown
          message: |
            *Repository* — ${{ github.repository }}
            *Owner* — ${{ github.actor }}
            *PR name* — ${{ github.event.pull_request.title }}
            *Message* — ${{ env.commitmsg || '📭' }}
            *Ref* — ${{ github.ref }}
            *SHA* — ${{ github.sha }}
            [PR URL](https://github.com/${{ github.repository }}/pull/${{ github.event.number }})
